# Generated by Django 5.1.1 on 2024-09-19 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='first_login',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='last_login',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='licence',
            name='issued_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='licence',
            name='key',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='licence',
            name='type',
            field=models.CharField(blank=True, default='trial', max_length=50, null=True),
        ),
    ]
