# Generated by Django 5.1.1 on 2025-01-16 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licence', '0002_alter_device_first_login_alter_device_last_login_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='licence',
            name='max_devices',
            field=models.PositiveSmallIntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='licence',
            name='expiration_date',
            field=models.DateField(blank=True),
        ),
    ]
