# Generated by Django 5.1.1 on 2025-01-16 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('licence', '0003_licence_max_devices_alter_licence_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='mac',
            field=models.CharField(max_length=17),
        ),
    ]
